### ISSUE TITLE
Mirrors and `LibraryMirror.functions`

### ISSUE THREAD

**Issue by Goutte** [dkornishev/dherkin#1]
Hello !

My Dart VM does not know `lib.functions` in stepdef_provider.
I'm running the pretty recent 1.4.0-dev.6.9.

I haven't found in the `dart:mirror` doc a suitable replacement for this.

**Comment by dkornishev** [comment]
I fixed it.

Good luck and let me know how it goes  :)

2014-05-24 22:50 GMT-04:00 Antoine Goutenoir notifications@github.com:

**Comment by Goutte** [comment]
That solved this issue, thanks!

But I don't get it. Github tells me this repository has not been updated since 2013, but https://pub.dartlang.org/packages/dherkin shows `0.2.1` ?
