### ISSUE TITLE
Double output (execution?) for scenario outline with a missing step

### ISSUE THREAD

**Issue by dkornishev** [dkornishev/dherkin#18]

**Comment by Goutte** [comment]
I have an idea.

**Comment by dkornishev** [comment]
looks like not only on missing stepdefs

**Comment by Goutte** [comment]
I got it ! I can fix it.

We DO want a new background-generated context on **each** of the scenarios generated by the table outlines ?
Right now it is not the case, they share the same background.

**Comment by dkornishev** [comment]
in ruby-cucumber background is only printed once per feature

2014-06-22 13:42 GMT-04:00 Antoine Goutenoir notifications@github.com:

**Comment by Goutte** [comment]
Yeah, I'm on it ;)

**Comment by Goutte** [comment]
Printed once, executed on each scenario, even table-generated scenarios.

PR is following.
