### ISSUE TITLE
Support for multiline variable

### ISSUE THREAD

**Issue by Goutte** [dkornishev/dherkin#2]
I need support for [multiline variables](http://docs.behat.org/guides/1.gherkin.html#pystrings) (encapsulated in `"""`, PyString-style), such as :

``` gherkin
  Scenario: Multiline variables
    Given I have the following multiline variable :
"""
line one
line two
"""
```

I could fork and try to add it myself, but this github repo is 0.2.0, not 0.2.1, so I'm cautious.

**Comment by dkornishev** [comment]
Github repo should be in order now.

The internals of the library are quite awkward due to sequential
parsing/futures not playing nicely together.
I am considering an overhaul at some point, but haven't had the time/energy

Good luck!

2014-06-09 17:49 GMT-04:00 Antoine Goutenoir notifications@github.com:

**Comment by Goutte** [comment]
Thanks!

The internals are not so awkward ; I wonder why you iterate over the results of each regex, though.
It might cause unwanted behavior (afaik) if you have something like :

``` gherkin
Feature: Working with "Feature: Recursive features :)"
```

Nonetheless, I got a basic feature working:

``` gherkin
Feature: Supporting PyStrings

    Scenario: Un-indented PyStrings
        Given I have the following PyString:
"""
line 1
line 2
"""
        Then the above Step should have the PyString as last parameter.
```

Of course, it will not yet work on indented PyStrings ; I'm still mulling over what should happen if we have a PyString _less_ indented than its opening/closing `"""`.
If it's _more_ indented, we can simply remove the extra leading whitespaces. Except if we're in tabs/spaces mixin' hell.

Also, should the runner raise an `Exception` if the PyString's closing `"""` are never found before the `EOF`, or silently ignore the data ?

---

### Checked Mode

It would be useful to use `assert()` in StepDefs, but when using `checked mode`, the runner crashes.

When I run `$ dart -c example/run.dart example/gherkin/pystrings.feature` :

```
Uncaught Error: type '_LocalClassMirror' is not a subtype of type 'MethodMirror' of 'mm'.
Stack Trace: 
#0      _scan.<anonymous closure>.<anonymous closure>.<anonymous closure> (file://dherkin/lib/dherkin.dart:54:63)
#1      Future.forEach.nextElement.<anonymous closure> (dart:async/future.dart:299)
#2      Future.Future.sync (dart:async/future.dart:168)
#3      Future.forEach.nextElement (dart:async/future.dart:299)
#4      Future.forEach (dart:async/future.dart:305)
#5      _scan.<anonymous closure>.<anonymous closure> (file://dherkin/lib/dherkin.dart:54:23)
#6      Future.Future.sync (dart:async/future.dart:168)
#7      _scan.<anonymous closure> (file://dherkin/lib/dherkin.dart:53:18)
#8      Future.forEach.nextElement.<anonymous closure> (dart:async/future.dart:299)
#9      Future.Future.sync (dart:async/future.dart:168)
#10     Future.forEach.nextElement (dart:async/future.dart:299)
#11     Future.forEach (dart:async/future.dart:305)
#12     _scan (file://dherkin/lib/dherkin.dart:52:19)
#13     run (file://dherkin/lib/dherkin.dart:34:8)
#14     main (file://dherkin/example/run.dart:6:6)
#15     _startIsolate.isolateStartHandler (dart:isolate-patch/isolate_patch.dart:214)
#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:124)


Unhandled exception:
type '_LocalClassMirror' is not a subtype of type 'MethodMirror' of 'mm'.
#0      _rootHandleUncaughtError.<anonymous closure>.<anonymous closure> (dart:async/zone.dart:713)
#1      _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:23)
#2      _asyncRunCallback (dart:async/schedule_microtask.dart:32)
#3      _asyncRunCallback (dart:async/schedule_microtask.dart:36)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:128)
```

Voodoo ! :see_no_evil:

**Comment by dkornishev** [comment]
I feel the project didn't come out faithful to the spirit of dart.  There
is also no way to run tests in parallel (which ruby-cucumber can).

> > Also, should the runner raise an Exception if the PyString's closing """ are
> > never found before the EOF, or silently ignore the data ?
> > I'd say that would make the file syntactically invalid and should throw an
> > exception
> > 
> > It would be useful to use assert() in StepDefs, but when using checked
> > mode, the runner crashes
> > I'll take a look.  Probably a case of ill-placed type annotation

Make a pull request for PyStrings  :)

2014-06-10 15:44 GMT-04:00 Antoine Goutenoir notifications@github.com:

**Comment by Goutte** [comment]
I added a handy `throw`, see PR #3. 

As for the spirit of dart, I'm too green to know what you mean !

**Comment by dkornishev** [comment]
I merged your PR and don't see any others.

@Spirit of Dart:

read this: https://www.dartlang.org/articles/event-loop/

Problem is that parsing is inherently a sequential-procedural operation.
 Most of dart, however, is futures/callbacks based.

Proper design would have one isolate doing parsing and handing off
completed scenarios to worker isolates to run.

2014-06-10 17:53 GMT-04:00 Antoine Goutenoir notifications@github.com:
