### ISSUE TITLE
Need a way to output messages that will appear at/near steps which causes them

### ISSUE THREAD

**Issue by dkornishev** [dkornishev/dherkin#21]
Currently, all messages from runners are printed before any gherkin output.  Need a way to print messages that will appear right after the step that caused them.

**Comment by Goutte** [comment]
That could be easily done if stepdefs were written inside a class extending FeatureContext class, as it could be a method of FeatureContext.

**Comment by Goutte** [comment]
Addtionnally, we could re-generate the buffer from the output `FeatureStatus`. That would mean storing the steps in order and using accessors for passing and failing.
