### ISSUE TITLE
Examples are not printed

### ISSUE THREAD

**Issue by dkornishev** [dkornishev/dherkin#26]
Examples need to be printed in the output

**Comment by dkornishev** [comment]
Now are printed but always green.  Need to figure out a way to mark failed example rows

**Comment by Goutte** [comment]
`final String _SPACER = "\t\t  ";`
Mixed indentation is the stuff the nightmares are from.

`Examples` is already colored, does it really need to be indented differently ?

**Comment by dkornishev** [comment]
Ruby-cucumber aligns it with the "Scenario" keyword.  I find this is more
readable.  At some point I'd love to re-do all output to use some
fixed-width library

2014-06-29 13:30 GMT-04:00 Antoine Goutenoir notifications@github.com:
