### ISSUE TITLE
Executing a feature many many times

### ISSUE THREAD

**Issue by Goutte** [dkornishev/dherkin#27]
I'm having a very weird bug and a hard time to expose it.

As you know, I'm running the spec suite once per spawned AI.
On the 454th, the stepdefs start complaining that their input variables (the ones extracted from the regex) are `null`.

This is puzzling, to say the least. What's worse, I don't know if it is a bug in Dart or in dherkin or in my runner.

Maybe the memory, garbage collection ?

**Comment by Goutte** [comment]
I can safely say it's not because my RAM is full.
Weirder and weirder...

**Comment by Goutte** [comment]
It's the `Step.unserialize()` method that is causing issues.

Apparently, when we call it too much, the `FormatException` raised by `int.parse()` also fills up the `unserialized` value with `null`.

I'm pretty sure this is a bug in Dart. The fix for dherkin is pretty simple, something like this works as expected :

``` dart
  static dynamic unserialize(String parameter) {
    var unserialized = parameter;
    var test = null;
    // Int ?
    try { test = int.parse(parameter); }
    on FormatException catch (_) {}
    // Num ?
    try { test = num.parse(parameter); }
    on FormatException catch (_) {}

    if (test != null) {
      unserialized = test;
    }

    return unserialized;
  }
```

I'm trying to set up a minimal test-case for the Dart team, because this will bite us again where it hurts eventually.

**Comment by dkornishev** [comment]
yeah, file a bug on dart

2014-06-23 9:42 GMT-04:00 Antoine Goutenoir notifications@github.com:

**Comment by Goutte** [comment]
Here's the [bug report about int.parse()](https://code.google.com/p/dart/issues/detail?id=19613).

Feel free to :star:  it, so that it gets attention.

**Comment by Goutte** [comment]
Let's keep this open until they solve the issue, so that we remember to revert the hotfix I'm pushing.

**Comment by Goutte** [comment]
We can keep this open until the release of dart 1.5.0, as it seems like it's fixed in the bleeding edge.

**Comment by Goutte** [comment]
I also [reported this](https://code.google.com/p/dart/issues/detail?id=19639). I bet you agree. :)

**Comment by Goutte** [comment]
Dart 1.5.1 was released ! This ought to disappear.

**Comment by dkornishev** [comment]
Something I did caused scenario outlines to be printed as many times as
there are rows in examples.  Any ideas?

2014-06-28 13:12 GMT-04:00 Antoine Goutenoir notifications@github.com:
