### ISSUE TITLE
Thin out gherkin_model.dart

### ISSUE THREAD

**Issue by dkornishev** [dkornishev/dherkin#32]
It has been invaded by a lot of new classes.
Some of them should move to a different file.

**Comment by Goutte** [comment]
I'm partisan of "one class per file", I dumped everything into gherkin_model because that's where everything was. Wanna do it, or shall I ?

**Comment by dkornishev** [comment]
I think one class per file is excessive.  Not to mention the need for 'part of' and 'part' directives
