### ISSUE TITLE
Features are run twice

### ISSUE THREAD

**Issue by Goutte** [dkornishev/dherkin#6]
When i run multiple feature files :

``` dart
main(args) {
  run([
      '../features/one.feature',
      '../features/two.feature'
  ]);
}
```

It seems that each feature is run twice.

**Comment by Goutte** [comment]
I suspected as much, but if I run three features, they're all run thrice.

Maybe I'm not providing the arguments properly ? I'm checking dherkin's "runner" source to find the cause for this, but no cheese.

---

Might also be useful to provide glob support `*` in filepaths, while we're at it ?

**Comment by dkornishev** [comment]
Interesting.  Haven't seen that before.  Yes, allowing for a whole
directory to be run would be nice

2014-06-11 20:29 GMT-04:00 Antoine Goutenoir notifications@github.com:

**Comment by dkornishev** [comment]
confirmed.  Will dig deeper this evening/tomorrow

**Comment by dkornishev** [comment]
Not run twice, printed twice.  Fixed by clearing output buffer on flush.
